version: '3.4'

services:
  php:
    build:
      context: .
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ../src:/var/www/html:cached
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx/log/:/var/log/nginx/
      - ./php.ini:/etc/php.ini
      - ./openswoole.ini:/etc/php.d/openswoole.ini
    working_dir: /var/www/html

  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}_nginx
    volumes:
      - ../src:/var/www/html:cached
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log/:/var/log/nginx/
    command: nginx -g "daemon off;"
    ports:
      - 80:80

  db:
    image: mysql:8.0
    volumes:
      - ./db/:/db
    container_name: ${PROJECT_NAME}_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_pma
    environment:
      PMA_HOST: db
      PMA_USER : root
      PMA_PASSWORD : ${MYSQL_ROOT_PASSWORD}
    ports:
      - 8080:80
      - 8000:8000

  redis:
    image: redis:6.0
    volumes:
      - ./redis/redis_data:/data
    container_name: ${PROJECT_NAME}_redis
    command: redis-server --appendonly yes

  mailcatcher:
    image: schickling/mailcatcher
    container_name: ${PROJECT_NAME}_mailcatcher
    ports:
      - "1080:1080"

  Memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
